// flipflop-sdk-sample-vue/src/components/VideoStreamer.vue
<template>
  <div class="streamer-container">
    <h2>Streamer</h2>
    <p>{{ streamState }}</p>
    <div style="margin-bottom: 10px;" v-if="videoKey !== ''"><span>videoKey: </span>&nbsp;&nbsp;<span>{{ videoKey }}</span></div>
    <div style="display:flex"><label style="margin-right: 5px">appKey</label><input :disabled="streamState !== 'Initialized'" type="text" v-model="appKey" placeholder="appKey"></div>
    <div style="display:flex"><label style="margin-right: 5px">appSecret</label><input :disabled="streamState !== 'Initialized'" type="text" v-model="appSecret" placeholder="appSecret" style="margin-bottom: 10px"></div>
    <div class="button-group">
      <button :disabled="streamState !== 'Initialized'" @click="init">init</button>
      <button :disabled="streamState !== 'Prepare'" @click="start">start</button>
      <button :disabled="streamState !== 'Started'" @click="stop">stop</button>
    </div>
    <video
      id="screen-video"
      width="1080"
      height="720"
      muted
      autoPlay
      playsInline
    ></video>
    <div class="video-chat-group">
      <div class="message-scroller">
        <div><span>{{ chatState }}</span></div>
        <div v-for="(messageItem, index) in messages" :key="messageItem.name + '-' + index">
          <div><span>{{ messageItem.user.username }}</span>&nbsp;&nbsp;<span>{{messageItem.message}}</span></div>
        </div>
      </div>
    </div>
      <form class="chat-form" v-on:submit="send">
        <input type="text" v-model="message" placeholder="type chat message...">
        <button>Send</button>
      </form>
  </div>
</template>

<script>
import { FlipFlop } from 'flipflop-sdk-javascript/dist/flipflop'
export default {
  name: 'VideoStreamer',
  data: () => ({
    appKey: '',
    appSecret: '',
    userId: 'ADMIN',
    userName: 'ADMIN',
    streamState: 'Initialized',
    chatState: 'Waiting',
    messages: [],
    message: '',
    videoKey: ''
  }),
  methods: {
    send (e) {
      e.preventDefault()

      if (this.message.trim().length === 0) {
      // Toast.warn('Enter messages to send')
        return
      }

      this.streamer.sendMessage(this.message)
      this.message = ''
    },
    async init () {
      if (!this.appKey || !this.appSecret) {
        alert('appKey and appSecret is required')
      }

      if (!this.streamer) {
        await FlipFlop.initialize(this.appKey, this.appSecret)
        this.sdk = await FlipFlop.authentication(this.userId, this.userName)
        this.streamer = this.sdk.getStreamer()
        const StreamerDelegate = {
          onPrepare: () => {
            this.streamState = 'Prepare'
          },
          onStart: (title) => {
            this.streamState = 'Started'
          },
          onStop: () => {
            this.streamState = 'Stopped'
          },
          onCompleted: () => {
            this.streamState = 'onCompleted'
          },
          onConnectSuccess: () => {
            this.chatState = 'Connected'
          },
          onConnectFailure: () => {
            this.chatState = 'Failure'
          },
          onChatReceived: (message) => {
            message.elapsedTime = Date.now() - message.created_at
            console.log('1234', this.messages)

            this.messages = this.messages.concat(message)
          }
        }
        this.streamer.delegate = StreamerDelegate
        const previewVideo = document.getElementById('screen-video')
        this.streamer.prepare(previewVideo)
      }
    },
    async start () {
      this.video = await this.streamer.start('Sample Title', 'Sample Content')
      console.log('HERE IS THE VIDEO ****************')
      console.log('this.video', this.video)
      this.videoKey = this.video.video_key
    },
    stop () {
      if (!window.confirm('Do you want to stop LIVE?')) {
        return
      }

      if (this.streamer) {
        this.streamer.stop()
      }
    }
  },
  async mounted () {
  },
  async unmounted () {
    if (this.streamer) {
      this.streamer.reset()
    }
  }
}
</script>
<style scoped>
.streamer-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.button-group {
  display: flex;
  justify-content: center;
  align-items: center;
}

.button-group button + button {
  margin-left: 10px;
}

.video-chat-group {
    height: 500px;
    overflow: scroll;
    width: 1080px;
    display: flex;
    text-align: left;
}

.message-scroller * {
  overflow-anchor: none;
}

.message-scroller:after {
  content: "";
  display: block;
  overflow-anchor: auto;
  height: 1px;
}
</style>

// flipflop-sdk-sample-react/src/video/VideoStreamer.js
import React from 'react'
import Configs from '../Configs';
import ChatList from './ChatList'
import VideoGoodsSelector from './VideoGoodsSelector';
import { bindActionCreators } from 'redux';
import { actions as videoActions } from '../modules/video';
import { connect } from 'react-redux';
import { FlipFlop } from 'flipflop-sdk-javascript/dist/flipflop'
import Play from '../svg/Play'
import Stop from '../svg/Stop'
import LiveView from '../svg/LiveView'
import FormBullet from '../svg/FormBullet'
import LiveBadge from '../svg/LiveBadge';
import { isWebRTCSupported } from '../support/browser'
import "./VideoStreamer.css"

const PARAM_APP_KEY = 'appKey'
const PARAM_APP_SECRET = 'appSecret'

class VideoStreamer extends React.Component {
  request = null
  flipflopSDK = null
  videoNode = null
  gossip = null

  state = {
    video: null,
    videoKey: "",
    streamState: 'initialized',
    messages: [],
    itemKeys: [],
    items: []
  }

  componentDidMount = () => {    
    if(!isWebRTCSupported()) {
     alert("browser doesn't support webrtc")
    };

    this.initToken()
  }
  
  initToken = async () => {
    const urlParams = new URLSearchParams(window.location.search);
    const appKey = urlParams.get(PARAM_APP_KEY)
    const appSecret = urlParams.get(PARAM_APP_SECRET)

    if (!appKey || !appSecret) {
      alert('appKey and appSecret parameters are required');
      return;
    }
    
    const randomUserId = Math.floor(Math.random() * 10001)
    let userId = localStorage.getItem('demo.user_id')
    let userName = localStorage.getItem('demo.user_name')

    if(!userId) {
      userId = randomUserId
      localStorage.setItem('demo.user_id', userId);
    }

    if(!userName) {
      userName = 'user-' + randomUserId
      localStorage.setItem('demo.user_name', userName);
    }

    console.log(`appKey: ${appKey}, appSecret: ${appSecret}, userId: ${userId}, userName: ${userName}`);

    FlipFlop.initialize(appKey, appSecret);
    this.sdk = await FlipFlop.authentication(userId, userName);
    this.setState({ appKey, appSecret, userId });
    
    this.streamer = this.sdk.getStreamer()
    this.streamer.delegate = this

    this.setVideo({ 
      title: 'Sample Live title...', 
      content: 'Sample Live content...', 
      user_id: userId, 
      user_name: userName,
      user_avatar_url: Configs.DEFAULT_AVATAR
     })
  }

  componentWillUnmount = () => {
    if (this.streamer) {
      this.streamer.reset()
    }
  }

  createRequest = (userId) => {
    this.request = {
      title: 'Sample Live title...',
      content: 'Sample Live content...',
      user_id: userId,
      user_name: 'streamer-' + userId,
      user_avatar_url: Configs.DEFAULT_AVATAR
    }
  }

  setVideo = (video) => {
    this.setState({ video })

    if (this.streamer) {
      this.streamer.prepare(this.videoNode)
    }
  }

  setStreamState = (streamState) => {
    console.log(`--- janus state: ${streamState}`)
    this.setState({ streamState })
  }

  stop = () => {
    if (!window.confirm('Do you want to stop LIVE?')) {
      return
    }
    
    if (this.streamer) {
      this.streamer.stop()
    }

    this.setState({ items: [] })
  }

  start = async () => {
    const { items } = this.state

    if (this.streamer) {
      const video = await this.streamer.start(
        this.state.video.title,
        this.state.video.content,
        JSON.stringify({goods_list: items})
      )

      this.setState({videoKey: video.video_key})

      video.state = "LIVE"

      localStorage.setItem('demo.video', 
        JSON.stringify(video))
    }
  }

  viewLive = () => {
    const urlParams = new URLSearchParams(window.location.search);
    const appKey = urlParams.get(PARAM_APP_KEY)
    const appSecret = urlParams.get(PARAM_APP_SECRET)

    window.open(`/videos/${this.state.videoKey}?appKey=${appKey}&appSecret=${appSecret}`);
  }

  prepare = () => {
    window.location.reload(true);
  }

  onClick = (item) => {
    console.log(item)

    const { items } = this.state
    const index = items.findIndex(i => i.id === item.id)
    
    if (items && index >= 0) {
      items.splice(index, 1)
    } else {
      items.push(item)
    }

    console.log(items)  
    this.setState({ items })
  }
  
  onPrepare = () => {
    console.log('onPrepare')
    this.setStreamState('Ready')
  }

  onStart = (streamName) => {
    console.log(`onStart: ${streamName}`)
    this.setStreamState('Started')
  }

  onStop = () => {
    console.log(`onStopped`)
    this.setStreamState('Stopped')
  }

  onCompleted = () => {
    console.log(`onCompleted`)
  }

  onChatReceived = (message) => {
    message.elapsedTime = Date.now() - message.created_at
    console.log(message);
    
    const { messages } = this.state;
    this.setState({ messages: messages.concat(message) });
  }

  onError = (error) => {
    if (error){
      console.error(error)
    }
  }

  render() {
    if (this.state.video === null) {
      return null
    }

    const { video, streamState, messages } = this.state

    return (
      <div className="video-stream-container">
        <div className="video-stream-group">
          <div className="video-viewer-header">
            <div className="video-title-group">
              <h6 className="title">{video.title}</h6>
              <p>{video.content}</p>
              <div><span className="content"><FormBullet/>{`User ID:${video.user_id}`}</span><span className="content"><FormBullet/>{`Stream state: ${streamState}`}</span></div>
            </div>
            <div className="video-button-group">
              {streamState === 'Ready' ? 
                <button type="button" className="common-button large-button red-button" onClick={this.start}><Play />Start Live</button> : 
                  streamState === 'Started' ?
                    <div style={{display: 'flex'}}>
                      <button type="button" className="common-button large-button white-button" onClick={this.viewLive} style={{marginRight: '5px'}} ><LiveView /><span>View Live</span></button>
                      <button type="button" className="common-button large-button white-button" onClick={this.stop}><Stop /><span>Stop Live</span></button>
                    </div> :
                  streamState === 'Stopped' && ''}
            </div>
          </div>
          <div className="video-viewer">
            <div className="video-view-group">
              <div className="video-view-bg">
                {streamState === 'Started' && <div className="video-badge"><LiveBadge /></div>}
                <video id="screenvideo" className="stream-video" ref={node => this.videoNode = node } width="100%" autoPlay playsInline></video>
              </div>
              <div>
                <VideoGoodsSelector items={this.state.items} onClick={this.onClick} />
              </div>
            </div>
            <div className="video-chat-group">
              <ChatList type="pc" messages={messages} />
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default connect(
	({ video }) => ({
    sdk: video.sdk
  }),
	(dispatch) => ({
    actions: bindActionCreators(videoActions, dispatch)
  })
)(VideoStreamer)
